services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tt1-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tt1-network

networks:
  tt1-network:
