sonar.projectKey=daargaiz_TT1Trabajo
sonar.organization=daargaiz

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=src/test/java/**