name: Publicar Javadoc
on:
  push:
    branches:
      - main
jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generar Javadoc
        working-directory: proyecto
        run: mvn javadoc:javadoc -Dmaven.javadoc.failOnError=false
      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: proyecto/target/reports/apidocs
          branch: gh-pages